# Generated by Django 2.2.16 on 2020-10-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='meal_distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Meal_names', models.TextField(default='N/A')),
                ('Meal_times', models.TextField(default='N/A')),
                ('Meal_calories', models.TextField(default='N/A')),
            ],
        ),
    ]
