# Generated by Django 2.2.16 on 2020-10-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_meal_distribution_user_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal_distribution',
            name='User_no',
            field=models.TextField(default='1'),
        ),
    ]
